import type { WpOrgPluginSource } from '../types'

export const wpOrgSources: WpOrgPluginSource[] = [
  {
    brand: 'WPForms',
    pluginSlug: 'wpforms-lite',
    pluginName: 'WPForms Lite',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/wpforms-lite/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'AIOSEO',
    pluginSlug: 'all-in-one-seo-pack',
    pluginName: 'All in One SEO',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/all-in-one-seo-pack/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'WP Mail SMTP',
    pluginSlug: 'wp-mail-smtp',
    pluginName: 'WP Mail SMTP',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/wp-mail-smtp/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'MonsterInsights',
    pluginSlug: 'google-analytics-for-wordpress',
    pluginName: 'MonsterInsights',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/google-analytics-for-wordpress/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'OptinMonster',
    pluginSlug: 'optinmonster',
    pluginName: 'OptinMonster',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/optinmonster/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'SeedProd',
    pluginSlug: 'coming-soon',
    pluginName: 'SeedProd',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/coming-soon/trunk/README.txt',
    accessDefault: 'public',
  },
  {
    brand: 'Duplicator',
    pluginSlug: 'duplicator',
    pluginName: 'Duplicator',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/duplicator/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'AffiliateWP',
    pluginSlug: 'affiliatewp-allowed-products',
    pluginName: 'AffiliateWP Allowed Products',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/affiliatewp-allowed-products/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'SearchWP',
    pluginSlug: 'searchwp-live-ajax-search',
    pluginName: 'SearchWP Live Ajax Search',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/searchwp-live-ajax-search/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'Easy Digital Downloads',
    pluginSlug: 'easy-digital-downloads',
    pluginName: 'Easy Digital Downloads',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/easy-digital-downloads/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'Smash Balloon',
    pluginSlug: 'custom-facebook-feed',
    pluginName: 'Smash Balloon Social Post Feed',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/custom-facebook-feed/trunk/README.txt',
    accessDefault: 'public',
  },
  {
    brand: 'Smash Balloon',
    pluginSlug: 'instagram-feed',
    pluginName: 'Smash Balloon Instagram Feed',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/instagram-feed/trunk/README.txt',
    accessDefault: 'public',
  },
  {
    brand: 'Smash Balloon',
    pluginSlug: 'custom-twitter-feeds',
    pluginName: 'Smash Balloon Twitter Feed',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/custom-twitter-feeds/trunk/README.txt',
    accessDefault: 'public',
  },
  {
    brand: 'Smash Balloon',
    pluginSlug: 'feeds-for-youtube',
    pluginName: 'Smash Balloon YouTube Feed',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/feeds-for-youtube/trunk/README.txt',
    accessDefault: 'public',
  },
  {
    brand: 'WP Simple Pay',
    pluginSlug: 'stripe',
    pluginName: 'WP Simple Pay',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/stripe/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'PushEngage',
    pluginSlug: 'pushengage',
    pluginName: 'PushEngage',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/pushengage/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'WPCode',
    pluginSlug: 'insert-headers-and-footers',
    pluginName: 'WPCode',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/insert-headers-and-footers/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'RafflePress',
    pluginSlug: 'rafflepress',
    pluginName: 'RafflePress',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/rafflepress/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'TrustPulse',
    pluginSlug: 'trustpulse-api',
    pluginName: 'TrustPulse',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/trustpulse-api/trunk/README.txt',
    accessDefault: 'public',
  },
  {
    brand: 'Charitable',
    pluginSlug: 'charitable',
    pluginName: 'Charitable',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/charitable/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'Sugar Calendar',
    pluginSlug: 'sugar-calendar-lite',
    pluginName: 'Sugar Calendar Lite',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/sugar-calendar-lite/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'Envira Gallery',
    pluginSlug: 'envira-gallery-lite',
    pluginName: 'Envira Gallery Lite',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/envira-gallery-lite/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'Soliloquy',
    pluginSlug: 'soliloquy-lite',
    pluginName: 'Soliloquy Lite',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/soliloquy-lite/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'UserFeedback',
    pluginSlug: 'userfeedback-lite',
    pluginName: 'UserFeedback Lite',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/userfeedback-lite/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'WPConsent',
    pluginSlug: 'cookie-notice-and-consent-banner',
    pluginName: 'WPConsent',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/cookie-notice-and-consent-banner/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'Uncanny Automator',
    pluginSlug: 'uncanny-automator',
    pluginName: 'Uncanny Automator',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/uncanny-automator/trunk/readme.txt',
    accessDefault: 'public',
  },
  {
    brand: 'Uncanny Owl',
    pluginSlug: 'uncanny-learndash-toolkit',
    pluginName: 'Uncanny LearnDash Toolkit',
    trunkReadmeUrl: 'https://plugins.svn.wordpress.org/uncanny-learndash-toolkit/trunk/readme.txt',
    accessDefault: 'public',
  },
]
